---
title: "Olympic 2020 Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    logo: olympic-games.png
    orientation: rows
    vertical_layout: scroll
    css: www/styles.css
    theme:
      version: 4
      bootswatch: lumen
      base_font: !expr bslib::font_google("Prompt")
      code_font: !expr bslib::font_google("Poppins")
---


```{r, include=FALSE}
library(readr)
library(readxl)
library(ggplot2)
library(flexdashboard)
library(tidyr)
library(dplyr)
library(highcharter)
library(plotly)
library(janitor)
library(bslib)
library(thematic)
library(knitr)

theme_set(theme_bw(base_size = 20))
```

```{r load data, message=FALSE, warning=FALSE}
athletes <- read_excel("data/Athletes.xlsx") %>% clean_names()
entry_gender <- read_excel("data/EntriesGender.xlsx")%>% clean_names
coaches <- read_excel("data/Coaches.xlsx") %>% clean_names()
medals <- read_excel("data/Medals.xlsx",
                         col_types = c("numeric", "text", "numeric", 
                                       "numeric", "numeric", "numeric", 
                                       "numeric")) %>% clean_names()
teams <- read_excel("data/Teams.xlsx") %>% clean_names()
```



```{r metrics analytics}
total_athletes <- athletes%>%nrow()
#total_coach <- coaches %>% nrow()
total_medal <- sum(medals$total)
total_country <- athletes %>% distinct(noc)%>%nrow()
total_games <- athletes %>% distinct(discipline)%>%nrow()
```





Value Boxes {data-width=200}
-------------------------------------

### Atheletes

```{r}
valueBox(total_athletes, caption = "Atheletes", color = "#018dce", icon = "fa-users")
```

### Country 

```{r}
valueBox(total_country, caption = "Country", color = "#0daf57", icon = "fa-flag")
```

### Games

```{r}
valueBox(total_games, caption = "Games", color = "#e33c54", icon = "fa-trophy")
```

### Medals

```{r}
valueBox(total_medal, caption = "Medals", color = "#f6b83a", icon = "fa-star")
```


3rd Party Outputs {.tabset data-height=700}
-------------------------------------


### Total Athletes Based on Country
    
```{r}
athletes_country <- read_csv("data/athletes_country.csv")


hcmap(
  "custom/world-robinson-highres", 
  data = athletes_country,
  name = "Total Athletes", 
  value = "count",
  borderWidth = 0,
  nullColor = "#d3d3d3",
  joinBy = c("iso-a3", "iso3")
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1))
    ) 
```

### Total Coach Based on Country
    
```{r}
athletes_country <- read_csv("data/athletes_country.csv")

coach_country <- coaches %>% group_by(noc) %>%
  summarise(coach_count = n())

coach_country <- coach_country %>% left_join(athletes_country, by= "noc") %>% select(iso3,noc,coach_count)

hcmap(
  "custom/world-robinson-highres", 
  data = coach_country,
  name = "Total Coach", 
  value = "coach_count",
  borderWidth = 0,
  nullColor = "#d3d3d3",
  joinBy = c("iso-a3", "iso3")
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1))
    ) 
```


### Total Medal Based on Country
    
```{r}
athletes_country <- read_csv("data/athletes_country.csv")
medal_country <- medals%>% left_join(athletes_country, by = c("team_noc"= "noc")) %>%
  select(iso3,team_noc,total)

hcmap(
  "custom/world-robinson-highres", 
  data = medal_country,
  name = "Total Medals", 
  value = "total",
  borderWidth = 0,
  nullColor = "#d3d3d3",
  joinBy = c("iso-a3", "iso3")
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1))
    ) 
```


Row {data-height=800}
-------------------------------------

### Country
    
```{r}
table_data <- athletes_country %>%
  left_join(coach_country,by="iso3")%>%
  left_join(medal_country,by="iso3")%>%
  select(`noc.x`,count,coach_count, total) %>%
  rename('NOC'='noc.x','Players'='count','Coach'='coach_count','Medals' ='total') %>%
  left_join(medals, by=c("NOC" ="team_noc")) %>%
  select(NOC, Players, Coach, gold,silver,bronze,Medals)%>%
  rename('Gold'='gold','Silver'='silver','Bronze'='bronze') %>%
  replace(is.na(.), 0)
```

```{r}
library(DT)
renderDataTable({
  DT::datatable(
    table_data,
    extensions = c('Scroller'),
    options = list(columnDefs = list(list(className = 'dt-center', targets = 0:4))
            ,
      dom = 'Blfrtip',
      deferRender = T,
  scrollY = '800px',
  scroller = TRUE))})
```


